Implement week picker component
Hacker0x01/react-datepicker pull request #2768
Opened 2021-02-26 16:10 UTC by TiesWestendorp

2021-03-01 15:22 UTC, TiesWestendorp commented
@martijnrusschen or someone else, can you take a look at this PR, and give your take on the questions I posed above?

2021-03-03 13:39 UTC, tlehtimaki commented
Q2: I think the selecting of all dates in the week seems logical, but then I think you should not be able to individually select the dates.
Q1: For how its implemented now the up/down arrows are logical for browsing the week. The browsing of month suddenly with left/right arrow might be confusing for the user, if user is used to browsing days with those keys.

2021-03-03 14:53 UTC, TiesWestendorp commented
> Q2: I think the selecting of all dates in the week seems logical, but then I think you should not be able to individually select the dates.

My question was actually more geared towards the internal state; each day component has a 'selected' and 'keyboard-selected' state, which I reuse for the week picker here. Another way would be to not consider these days selected or keyboard-selected in this case, but the week component that wraps these days. There's a bit of a trade-off here: the former option borrows heavily from the existing styling, meaning it doesn't introduce much complexity in the stylesheets, but is potentially less flexible. As to your comment: clicking on a particular date will currently select the corresponding date - do you mean to say that you don't agree with this? My issue with that is that when the week numbers are not present you won't have a meaningful thing to click on. A takeaway from this may be that the week numbers should always be shown when the week picker is used, but that is also currently not the case.

> Q1: For how its implemented now the up/down arrows are logical for browsing the week. The browsing of month suddenly with left/right arrow might be confusing for the user, if user is used to browsing days with those keys.

I agree, but wanted to lay the options on the table. :+1: Currently left/right behave the same as up/down in the week picker.

2021-03-03 15:15 UTC, tlehtimaki commented
I understood that the concept would be to select just weeks, so I thought there would be no need to select a single date, but here that single date would convert in to the week that the date belongs to.

2021-03-03 15:57 UTC, TiesWestendorp commented
> I understood that the concept would be to select just weeks, so I thought there would be no need to select a single date, but here that single date would convert in to the week that the date belongs to.

Correct, just having the week number select the first date of a week was already possible by using a callback on the week number. What this PR introduces is the additional logic required to properly display the state, changed keyboard navigation to match and a fallback that ensures the first day of a week is always used.

2021-03-10 15:34 UTC, TiesWestendorp commented
Could some one take a look at why the specs are failing? I'm not really sure what's going wrong.

2021-03-10 15:35 UTC, martijnrusschen commented
Can you try to pull the latest master in? I think the issue was fixed
earlier.

On Wed, 10 Mar 2021 at 16:34 TiesWestendorp <notifications@github.com>
wrote:

> Could some one take a look at why the specs are failing? I'm not really
> sure what's going wrong.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/Hacker0x01/react-datepicker/pull/2768#issuecomment-795613248>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKY2KGRGC53MJQRT7XBZOTTC6GQVANCNFSM4YIWJW4Q>
> .
>

2021-03-10 16:09 UTC, TiesWestendorp commented
The failing spec seems to be fixed by rebasing, but I'm still getting errors during linting...

2021-03-10 16:17 UTC, martijnrusschen commented
It looks like something happened with the rebase, seeing some changes in the PR that already got merged. Regarding the lint errors, it seems they're related to the changes in this PR.

2021-03-31 11:45 UTC, martijnrusschen commented
Checking in, can you merge with the latest master so we can release this functionality?

2021-04-07 14:15 UTC, TiesWestendorp commented
> Checking in, can you merge with the latest master so we can release this functionality?

Did so just now, that at least cleans up the git history. :+1: I'm still not sure about the lint errors though. :shrug:

2021-04-21 07:22 UTC, mykolap commented
And proper format string for year/week will also be supported for this peeker? Currently we are forced to use literals "ww/YYY", with 3 letters Y, instead of YY or YYYY, because date-fns rejects ww/YYYY or ww/YY. And week should be used only with big Y, not small y. See https://github.com/Hacker0x01/react-datepicker/issues/2661. Week peeker without support of WeekYear tokens in date-fns will be not complete.

2021-04-21 07:43 UTC, TiesWestendorp commented
> And proper format string for year/week will also be supported for this peeker? Currently we are forced to use literals "ww/YYY", with 3 letters Y, instead of YY or YYYY, because date-fns rejects ww/YYYY or ww/YY. And week should be used only with big Y, not small y. See #2661. Week peeker without support of WeekYear tokens in date-fns will be not complete.

I'm not really familiar with the problem you're describing. The only thing that's important for this PR, is that `date-fns` is able to parse the the given format, and that in doing so it returns a date that corresponds to the first calendar cell in a given week. In the given example this means I've used the format `I/R`.

2021-04-21 07:57 UTC, mykolap commented
To show start of week correctly - you should pass locale to dateFns, after that if locale German - you will get Monday as a start, if US - Sunday, but issue is with year, because year for week and calendar year - are different, and only hack with 3 letters Y is working when we want to handle year correcly... And it's very ugly hack...

2021-04-22 08:18 UTC, TiesWestendorp commented
> To show start of week correctly - you should pass locale to dateFns, after that if locale German - you will get Monday as a start, if US - Sunday, but issue is with year, because year for week and calendar year - are different, and only hack with 3 letters Y is working when we want to handle year correcly... And it's very ugly hack...

I would say that this seems like a separate issue from what's being done in this PR. _Given_ that `format` and `parse` work correctly, the changes from this PR work correctly.

2021-04-22 12:01 UTC, TiesWestendorp commented
@martijnrusschen I've fixed the lint errors. Could you take a look at this PR?

2021-04-22 12:05 UTC, martijnrusschen commented on src/day.jsx
> +    // TODO: use isStartOfWeek
Is this still something you want to change here?

2021-04-22 12:16 UTC, TiesWestendorp commented on src/day.jsx
> +    // TODO: use isStartOfWeek
I think I just forgot to remove a comment there.

2021-05-04 09:23 UTC, TiesWestendorp commented
@martijnrusschen Could you still have a look at this PR?

2021-05-05 14:29 UTC, martijnrusschen commented
This looks good! Can you resolve the merge conflict so I can merge it in? I'm preping a major release for this week and would love to get this in.

2021-05-06 07:32 UTC, TiesWestendorp commented
:+1: Done.

2021-05-06 07:41 UTC, martijnrusschen commented
I ran the tests, and it looks like there's some things breaking. Can you take a look?

2021-05-06 10:42 UTC, TiesWestendorp commented
Should be fixed now.

2021-05-06 13:15 UTC, martijnrusschen commented on test/week_picker_test.js
> +import React from "react";
Thinking a bit on code coverage.. Might be good to add some tests that checks the behavior of showing/hiding the weekpicker as well. Making sure the weekpicker isn't shown when the prop isn't passed in and shown when it is passed in.

2021-05-06 13:17 UTC, martijnrusschen commented on test/week_picker_test.js
> +import React from "react";
Codecov added some comments on coverage as well, would be great to improve the coverage to make sure we don't break this in the future.

2021-05-08 17:22 UTC, martijnrusschen requested changes
Let's improve the test coverage to make sure we won't break this in the future.

2021-05-27 15:03 UTC, georgecosmin98 commented
Hello!

Any news about week-picker? When can we expect a release?

2021-06-24 00:23 UTC, johnnyxbell commented
Any news on when we can get this merged?

2021-06-26 11:23 UTC, sffirm commented
Why is it taking so long?

2021-07-08 11:13 UTC, manzoorwanijk commented
Any update on this?

2021-07-19 09:34 UTC, nacimgoura commented
When will this feature be merged?

2021-07-19 15:36 UTC, arikm66 commented
I really need this feature :)  When will it be merged?

2021-07-20 20:31 UTC, martijnrusschen commented
Perhaps someone can take a look and bring this to the finish line.

2021-08-11 10:54 UTC, Seaviello commented
Hi,
we are also currently interested in that feature. Is there something that outsider can do to help you out with making this happen or right now it's mostly in the reviewers hand?

2021-10-04 06:39 UTC, akashraj9828 commented
Any update on this... really need this feature. Thanks in advance.

2021-10-05 07:51 UTC, akashraj9828 commented
Not sure if anyone needs this anymore but I was able to implement the week picker with the existing library... 
Demo: 
https://codesandbox.io/s/react-datepicker-example-forked-89fn7?file=/src/WeekPicker.tsx

2022-02-10 23:09 UTC, ngajhede commented
Hey @correahi! Thanks for this. I was wondering how you display the `startDate to endDate` in the input box?

2022-02-12 05:01 UTC, correahi commented
> Hey @correahi! Thanks for this. I was wondering how you display the `startDate to endDate` in the input box?

I don't have access to that codebase anymore but i'm pretty sure it's just a span with some text inside, something like `${startOfISOWeek(selectedDate)} to ${endOfISOWeek(selectedDate)}` and `onClick` it opens the datepicker, it's not the default input.

2022-07-10 12:20 UTC, closed without merging

2023-06-21 03:28 UTC, gtaylor44 commented
Will this be merged into master?