Support selecting multiple dates
Hacker0x01/react-datepicker pull request #3999
Opened 2023-04-14 19:45 UTC by nandorojo

Uploading React Datepicker crafted by HackerOne - 14 April 2023.mp4…

# What

This PR adds 2 props which allow users to select multiple isolated dates on the calendar picker.

You can now select multiple dates at once, which is very convenient for products that need users to select multiple dates, such as Calendly and the like.

# How

Following the API for `selectsRange`, this PR adds a `selectsMultiple` boolean, in addition to a `selectedDates` array.

I thought it was best for `selectedDates` to be explicitly different from `selected`. This is also following the convention from `selectsRange`, which uses `startDate` and `endDate`.

## Example

As shown in the video above, here is the example code:

```tsx
() => {
  const [selectedDates, setSelectedDates] = useState([new Date()]);
  const onChange = (dates) => {
    setSelectedDates(dates);
  }
  return (
    <DatePicker
      selectedDates={selectedDates}
      selectsMultiple
      onChange={onChange}
      shouldCloseOnSelect={false}
      disabledKeyboardNavigation
    />
  )
}
```

## Breakdown

This PR adds a few minor changes to achieve adding multiple dates.

First, in the `Picker` component, it adds 2 core changes:

1. Formatting the input with `safeMultipleDatesFormat`.
2. Properly accounting for selecting multiple dates in `onChange`.

The rest is just prop drilling down to `<Day />`, which has 2 key changes:

1. `isKeyboardSelected` needs to account for `selectedDates` rather than `selected`.
2. `isSelected` also checks for `selectedDates`

I've tested this out and it all looks good to me!

2023-06-30 14:23 UTC, nandorojo commented
Sure, other than the example app updates?

2023-06-30 14:25 UTC, martijnrusschen commented
Ideally, add some automated tests to ensure we don't break this in future changes. You can see the tests folder with examples of how to test.

2023-06-30 14:27 UTC, nandorojo commented
Got it, I can do that today if it means getting it merged. Thanks for the feedback.

2023-06-30 14:30 UTC, nandorojo commented on docs-site/src/examples/selectsMultiple.js
> +    <DatePicker
Normally I would, but I just copied what the other examples did.

2023-07-03 21:26 UTC, danMateer commented
**James D** and **Graham C** from PullRequest - any test cases you can recommend to @nandorojo just so he can knock them out?

I'm 100% sure he's fully capable, just very busy juggling a lot [1](https://github.com/nandorojo) [2](https://twitter.com/fernandotherojo). It helps sometimes to just have stuff listed in GitHub even if it's basic and obvious.

2023-08-22 01:16 UTC, garrettparris commented
any way to just merge this? useful feature and the code looks fine.

2023-09-11 04:35 UTC, williamtcastro approved these changes

2023-09-11 09:19 UTC, Zarthus commented
> any way to just merge this? useful feature and the code looks fine.

@garrettparris @williamtcastro @nandorojo 

Seems like it's currently blocked on some missing tests, we recently migrated to jest so hopefully it's easier to add tests now. There's also a merge conflict error.

2024-01-08 16:50 UTC, nandorojo commented
Hey guys. Is this worth me going into and fixing merge conflicts? I can do it, but I don't want to spend the time if it won't get merged.

We used the code in prod for months with no issues. However, I just upgraded to 4.14.0 and lost all my changes, so I'm hoping to use this PR now. Please let me know if this is worth doing or not.

2024-01-08 16:53 UTC, nandorojo commented
Merge conflicts fixed.

2024-01-08 16:53 UTC, nandorojo commented
Not sure where tests are failing, I don't see them on here.

2024-01-08 16:55 UTC, martijnrusschen commented
@nandorojo I've started the workflows for test coverage. You should see those showing up in a minute. Per request, can you add some test coverage for this functionality? I'm happy to get this merged once ready.

2024-01-08 16:56 UTC, martijnrusschen commented
Per workflow results, the codecov check is complaining about missing test coverage.

2024-01-08 19:38 UTC, martijnrusschen commented on test/multiple_selected_dates.test.js
> +  it("should have multiple highlighted days", () => {
It looks like you may have forgotten an expect in this test case.

2024-01-08 19:49 UTC, nandorojo commented on test/multiple_selected_dates.test.js
> +  it("should have multiple highlighted days", () => {
Yeah I was hoping to get some guidance on how to implement this one. I tried copying some helper functions from other tests but haven't been able to figure it out quite yet.

2024-02-02 15:48 UTC, nandorojo commented on test/multiple_selected_dates.test.js
> +  it("should have multiple highlighted days", () => {
Does anyone with more test / internals knowledge have guidance for these tests? I'm not totally sure what the requirement is

2024-02-19 11:32 UTC, tbowmo requested changes

2024-02-19 11:32 UTC, tbowmo commented on test/multiple_selected_dates.test.js
> +  it("should handle text format for multiple selections", () => {
for two selected dates

2024-02-19 11:32 UTC, tbowmo commented on test/multiple_selected_dates.test.js
> +  });
```js

  it("should handle text format for more than two selected dates", () => {
    const datePicker = getDatePicker({
      selectsMultiple: true,
      selectedDates: [new Date("2024/01/01"), new Date("2024/01/15"), new Date("2024/03/15"), ],
    });

    expect(datePicker.getByRole('textbox').value).toBe("01/01/2024 (+2)");
  });
```

2024-02-23 08:08 UTC, tbowmo commented on test/multiple_selected_dates.test.js
> +  it("should have multiple highlighted days", () => {
@nandorojo As I see it, the displaying of individual selected days should not be tested here. 

I have provided a new test that checks if the input text box is rendered properly with 2 and 2+ dates selected.

I have a larger project where this addition could be very useful.

2024-02-25 10:08 UTC, tbowmo requested changes

2024-02-25 10:08 UTC, tbowmo commented on test/multiple_selected_dates.test.js
> +    return TestUtils.renderIntoDocument(
```suggestion
    return render(
```

2024-02-25 10:08 UTC, tbowmo commented on test/multiple_selected_dates.test.js
> +import TestUtils from "react-dom/test-utils";
```suggestion
import { render } from "@testing-library/react";
```

2024-02-25 10:08 UTC, tbowmo commented on test/multiple_selected_dates.test.js
> +    expect(datePicker.input.value).toBe("01/01/2024, 01/15/2024");
```suggestion
    expect(datePicker.getByRole("textbox").value).toBe("01/01/2024, 01/15/2024");
```

2024-02-25 18:25 UTC, martijnrusschen commented
@nandorojo can you resolve the merge conflicts?

2024-02-25 20:05 UTC, tbowmo reviewed
Found a couple of minor issues (perhaps some is just nitpicking),

Not entirely sure about code coverage or how I can help with adding that without creating a new PR against @nandorojo s branch (if needed)

2024-02-25 20:05 UTC, tbowmo commented on src/date_utils.js
> +  if (!dates || !dates.length) {
```suggestion
  if (!dates?.length) {
```

2024-02-25 20:16 UTC, martijnrusschen commented
@tbowmo Thanks for the suggestions. It would be great to get this PR over the finish line. If it's easier, perhaps we should consider opening a new PR with your changes included. Let me know if you prefer that and I can review the changes once its in.

2024-02-25 21:22 UTC, tbowmo commented
So you suggest that I fork @nandorojo working branch, add my suggestions, and then create a new pr? (perhaps add a few tests when I get it figured out)

2024-02-28 13:26 UTC, merged

2024-06-27 23:07 UTC, luistorres commented on src/day.jsx
> +    if (this.props.selectsMultiple) {
Hi @nandorojo  👋 
Was digging into this PR to investigate "select multiple months" and I think we need logic similar to this for the months and weeks selection, otherwise there's no selection styles there.
Happy to help with it if I can