Add support second-level granularity to injectTimes
Hacker0x01/react-datepicker pull request #4683
Opened 2024-04-12 15:52 UTC by yykcool

---
name: Pull Request
about: Create a pull request to improve this repository
title: ""
labels: ""
assignees: ""
---

## Description
**Linked issue**: #(issue number) 

**Problem**

**Changes**

## Screenshots

## To reviewers

## Contribution checklist
- [ ] I have followed the [contributing guidelines](https://github.com/Hacker0x01/react-datepicker/blob/main/CONTRIBUTING.md).
- [ ] I have added sufficient test coverage for my changes.
- [ ] I have formatted my code with Prettier and checked for linting issues with ESLint for code readability.

2024-04-13 18:00 UTC, martijnrusschen requested changes
Please fix the test case comments

2024-04-14 12:24 UTC, yykcool commented
comments are addressed

2024-04-14 12:24 UTC, yykcool commented on test/inject_times_test.test.js
> +  it.only("should support hours, minutes, and seconds", () => {
resolved

2024-04-14 12:24 UTC, yykcool commented on test/inject_times_test.test.js
> +    console.log(Array.from(injectedItems).map((node) => node.textContent));
resolved

2024-04-14 12:41 UTC, martijnrusschen commented
Can you make sure to merge with the latest main branch to upload the code coverage file?

2024-04-14 12:58 UTC, yykcool commented
it seems like things are already up to date (tried to do a merge from the main branch), is there anything i might have missed?

2024-04-14 13:41 UTC, martijnrusschen commented
can you try again?

2024-04-14 13:57 UTC, yykcool commented
done

2024-04-14 16:45 UTC, merged